name: run OHV-HOST container
on: [push]
jobs:
  start-container:
    runs-on: ubuntu-latest
    container:
      image: mitchv85/ohv-host:latest
    steps:
      - name: commands on OHV-HOST container
        run: |
          cat /etc/os-release
          pip list
          ps -ef
